-- reports — published "Dispatches" (monthly state-of-the-fleet write-ups).
-- Generated by scripts/generate_dispatch.py (monthly-dispatch.yml) from the data
-- the crons collect, and rendered on the site by src/components/Dispatch.jsx.
-- unique (kind, period) lets the generator upsert the same month idempotently;
-- each row stores headline stats so the next dispatch can diff against it.

create table if not exists public.reports (
  id           uuid primary key default gen_random_uuid(),
  kind         text not null default 'monthly',
  period       text not null,                 -- e.g. '2026-06'
  title        text not null,
  body         text not null,                 -- markdown
  stats        jsonb,
  published_at timestamptz not null default now(),
  unique (kind, period)
);

alter table public.reports enable row level security;

create policy "public read reports"
  on public.reports for select
  using (true);

grant select on public.reports to anon, authenticated;
